### PR TITLE
fix: json serialization of `AggchainData`

### LINKED ISSUE #110: AggchainData broken json serialization
As noted by @tnobayashi 

> it looks like the admin API isn't responding correctly anymore
> 
> ```
> cast rpc admin_getCertificate $ID  --rpc-url=$URL
> Error: server returned an error response: error code -32603: Internal error
> 
> {"timestamp":"(...)","level":"ERROR","fields":{"message":"Error serializing response: Error(\"can only flatten structs and maps (got a sequence)\", line: 0, column: 0)"},"target":"jsonrpsee-server"}
> ```
> (EDITED)

### PR DESCRIPTION
**Pull request by iljakuklic**
* Fixes json serialization of `AggchainData` inside a `serde(flatten)`-ed struct field (e.g. in `Certificate`).
* Partially resolves #110

### CODE REVIEW

File: crates/agglayer-interop-types/src/aggchain_proof/mod.rs [hunk 1]
```diff
@@ -26,7 +26,9 @@ pub enum AggchainData {
         /// Optional aggchain proof public values.
         public_values: Option<Box<AggchainProofPublicValues>>,
     },
-    MultisigOnly(MultisigPayload),
+    MultisigOnly {
+        multisig: MultisigPayload,
+    },
```
Comment (iljakuklic) [inline crates/agglayer-interop-types/src/aggchain_proof/mod.rs:31]: Note, since it might not be obvious: this is the actual fix. The `#[serde(flatten)]` attribute, used in `Certificate`, does not play nice with tuple variants. It requires the contents to be a struct or a struct-variant.
